name: CI – Piscine 42

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🔁 Checkout du code
        uses: actions/checkout@v3

      - name: 🐍 Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: 📦 Installer Norminette
        run: |
          python3 -m pip install --upgrade pip setuptools
          python3 -m pip install norminette

      - name: Compiler et exécuter les tests
        run: |
            mkdir -p build
            # Compilations avec tests
            find tests -type f -name 'main.c' | while read -r t; do
              src=${t#tests/}
              exe="build/$(dirname "$src")"
              echo "🧪 Test $t -> $exe"
              cc -Wall -Werror -Wextra "$t" -o "$exe"
              "$exe"
            done


      - name: ▶️ Exécuter les binaires
        run: |
          for f in build/*; do
            echo "✔ Running $f"
            "$f" || exit 1
          done

      - name: ✅ Vérifier le style (Norminette)
        uses: alexandregv/norminette-action@v3
        with:
          flags: '.'
