name: CI – Piscine 42

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Installer Norminette
        run: |
          python3 -m pip install --upgrade pip setuptools
          python3 -m pip install norminette

      - name: Compiler les exercices
        run: |
          mkdir -p build
          for mod in C*/; do
            for ex in "$mod"/ex*/; do
              src=$(find "$ex" -maxdepth 1 -name 'ft_*.c')
              if [ -n "$src" ]; then
                bin="build/$(basename "$mod")_$(basename "$ex")"
                cc -Wall -Wextra -Werror $src -o "$bin"
              fi
            done
          done

      - name: Exécuter les binaires
        run: |
          for f in build/*; do
            echo "✔ Running $f"
            "$f" || exit 1
          done

      - name: Vérification avec Norminette
        uses: alexandregv/norminette-action@v3
        with:
          flags: '.'
