name: CI – Piscine 42

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installer Norminette
        run: python3 -m pip install -U pip setuptools norminette

      - name: Compiler & exécuter tests
        run: |
          mkdir -p build
          find tests -type f -name 'main.c' | while read -r t; do
            exe="build/$(basename "$(dirname "$t")")"
            cc -Wall -Wextra -Werror "$t" -o "$exe"
            "$exe"
          done

      - name: ▶️ Exécuter les binaires
        run: |
          shopt -s nullglob
          for f in build/*; do
            echo "✔ Running $f"
            "$f" || exit 1
          done

      - name: ✅ Lint style (Norminette)
        run: |
          files=$(find . -type f -name '*.c' ! -path './tests/*')
          output=$(norminette -R CheckForbiddenSourceHeader $files)
          echo "$output" | grep -v 'Error: INVALID_HEADER'
          if echo "$output" | grep -v 'Error: INVALID_HEADER' | grep 'Error:'; then
              echo "Erreur(s) autre(s) que INVALID_HEADER détectée(s)."
              exit 1
          fi